### ISSUE TITLE
Ping command crashes app when used multiple times in succession

### ISSUE THREAD

**Issue by DBAggie** [DBAggie/discordBot#1]
Current error message is:

`DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.deferReply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:61:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:8:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:12:5) {
  method: 'post',
  path: '/interactions/995804692976259132/aW50ZXJhY3Rpb246OTk1ODA0NjkyOTc2MjU5MTMyOkpLcm02UzRHNk5icmdvV2xsN2xxN3NRZFJlbzV3WTRybUR6MFI1dVNFQkdXT241VlkxSmFvU2szZUd3S3d4eFQ2MUZqWFRGbm1TeHpuSjBsVWdUWG9wczRpRUVDZ3ZTSERodGN5NDd5dTFxWUpwV0ZSZmp1WlhQVTdmZ1k5Rmps/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 5, data: [Object] }, files: [] }
}
C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94:46)
    at Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:15:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}`

**Comment by DBAggie** [comment]
Latest error message: 

`DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:8:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:12:5) {
  method: 'post',
  path: '/interactions/995807957147205752/aW50ZXJhY3Rpb246OTk1ODA3OTU3MTQ3MjA1NzUyOlhlVm15SjJXbjVXbTZpYjJ6MDhzcFkzOE5KVlZiUUN5MGJIVXlPZnlKblhiaml3VmVxQmNqQmZLeFVFOEFhVUxsZ0dES1FCa2dFRkFpVDRRWVZXSkRGaWVMR0w5eHU2dzNmWng0b21mQ3Rpa2RscWE3RFpiMmVpNE5BcXBJeEZI/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:8:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:12:5) {
  method: 'post',
  path: '/interactions/995807957071699968/aW50ZXJhY3Rpb246OTk1ODA3OTU3MDcxNjk5OTY4OjNmT3BWZWh1SE03Q3FGSkZaY29rMDQzb05NejhRN3Y1VlZIQXBldjE3VG50RFlZQXBwVndnbmtqUmFlRkFjbXptQjB0YmFHWnNpemwwdDFnMTNPR01LV2FHMXl2ZURzcmtxSThPV0dsN1lwRXdFOHdiWXhYUlZKQ0txaDR0S0xM/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:8:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:12:5) {
  method: 'post',
  path: '/interactions/995807957071699968/aW50ZXJhY3Rpb246OTk1ODA3OTU3MDcxNjk5OTY4OjNmT3BWZWh1SE03Q3FGSkZaY29rMDQzb05NejhRN3Y1VlZIQXBldjE3VG50RFlZQXBwVndnbmtqUmFlRkFjbXptQjB0YmFHWnNpemwwdDFnMTNPR01LV2FHMXl2ZURzcmtxSThPV0dsN1lwRXdFOHdiWXhYUlZKQ0txaDR0S0xM/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
`

**Comment by DBAggie** [comment]
Most recent Dev Branch Error Message: 


`DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:8:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:12:5) {
  method: 'post',
  path: '/interactions/995810430561820783/aW50ZXJhY3Rpb246OTk1ODEwNDMwNTYxODIwNzgzOnltZTZRZTRpTTVCN3c5bWFpa3MyUUFUMWFPVjk0Rm03cVpKeDJ4VGh2a3BESUxtZ3N3ZUhQUmFndEpSbVREbzZMUlVWV3pORmZJaUFoS3J6UVZ1ZkdpZ28wakpLWmlONzJTVjY5TFZwSUpMRXMyT1M5SEh4ZjV6TGt2Skd3Z25H/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}`
